spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bazaar_db
    username: root
    password: JulyNewCode@2023

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    table: users_history_schema_table
    baselineOnMigrate: true

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.type.mapping: "UserEvent:com.user.events.UserCreatedEvent"

    consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.type.mapping: "UserEvent:com.user.events.UserCreatedEvent,RewardEvent:com.user.events.ReferralRewardEvent"

        group-id: "SchedulerCoordinator1"

server:
  port: 8082
