server:
  port: 8081
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  application:
    name: PRODUCT-SERVICE

  h2:
    console:
      enabled: true
logging:
  level:
    root: INFO