server:
  port: 8084
spring:
  profiles:
    active: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  application:
    name: CART-SERVICE

  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO


