spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bazaar_db
    username: root
    password: JulyNewCode@2023

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094

    producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.type.mapping: "RewardEvent:com.cartService.events.UserCreatedEvent"

    consumer:
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
          spring.json.type.mapping: "UserEvent:com.cartService.events.UserCreatedEvent"

        group-id: "SchedulerCoordinator"

server:
  port: 8084

logging:
  level:
    root: INFO
